-- MySQL Script generated by MySQL Workbench
-- mar 18 jun 2024 20:10:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university` ;
USE `university` ;

-- -----------------------------------------------------
-- Table `university`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`students` (
  `students_id` INT NOT NULL AUTO_INCREMENT,
  `students_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`students_id`),
  UNIQUE INDEX `students_id_UNIQUE` (`students_id` ASC) VISIBLE,
  UNIQUE INDEX `students_name_UNIQUE` (`students_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`professors` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `professors_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`professor_id`),
  UNIQUE INDEX `professor_id_UNIQUE` (`professor_id` ASC) VISIBLE,
  UNIQUE INDEX `professors_name_UNIQUE` (`professors_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses` (
  `courses_id` INT NOT NULL AUTO_INCREMENT,
  `courses_name` VARCHAR(45) NOT NULL,
  `professor_id` INT NOT NULL,
  PRIMARY KEY (`courses_id`, `professor_id`),
  UNIQUE INDEX `courses_id_UNIQUE` (`courses_id` ASC) VISIBLE,
  UNIQUE INDEX `courses_name_UNIQUE` (`courses_name` ASC) VISIBLE,
  INDEX `fk_courses_professors_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_courses_professors`
    FOREIGN KEY (`professor_id`)
    REFERENCES `university`.`professors` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`grades` (
  `grades_id` INT NOT NULL AUTO_INCREMENT,
  `students_id` INT NOT NULL,
  `grade` DECIMAL(4,2) NOT NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`grades_id`, `courses_id`),
  UNIQUE INDEX `grades_id_UNIQUE` (`grades_id` ASC) VISIBLE,
  INDEX `fk_grades_courses1_idx` (`courses_id` ASC) VISIBLE,
  CONSTRAINT `fk_grades_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `university`.`courses` (`courses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`students_has_grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`students_has_grades` (
  `students_id` INT NOT NULL,
  `grades_id` INT NOT NULL,
  PRIMARY KEY (`students_id`, `grades_id`),
  INDEX `fk_students_has_grades_grades1_idx` (`grades_id` ASC) VISIBLE,
  INDEX `fk_students_has_grades_students1_idx` (`students_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_grades_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `university`.`students` (`students_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_grades_grades1`
    FOREIGN KEY (`grades_id`)
    REFERENCES `university`.`grades` (`grades_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
